version: "3.7"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1-alpine
    ports:
      - "${HOST}:443:443"
      - "${HOST}:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

  app:
    build:
      context: src
    volumes:
      - type: volume
        source: yarn_cache
        target: /yarn-cache
      - ./data/workspaces:/workspaces
    environment:
      - VIRTUAL_HOST=${DOMAIN}
    init: true

volumes:
  yarn_cache:
