version: "3.7"

services:
  redis:
    image: redis:6.0.8-alpine
    command: redis-server
    volumes:
      - type: volume
        source: redis_data
        target: /data

  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1-alpine
    ports:
      - "${HOST}:443:443"
      - "${HOST}:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

  app:
    build:
      context: src
    volumes:
      - type: volume
        source: yarn_cache
        target: /yarn-cache
      - ./data/workspaces:/workspaces
    environment:
      - VIRTUAL_HOST=${DOMAIN}
    depends_on:
      - redis
    init: true

volumes:
  redis_data:
  yarn_cache:
