version: "3.7"

services:
  app:
    build:
      context: src
    volumes:
      - type: volume
        source: yarn_cache
        target: /yarn-cache
      - ./data/workspaces:/workspaces
      - .env:/env/.env
      - ./data/config:/config
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${PUBLIC_DOMAIN}
      - ENV_FILE=/env/.env
      - CONFIG_DIR=/config
    init: true
    networks:
      - default

volumes:
  yarn_cache:

networks:
  default:
    external:
      name: vps-network
