version: "3.7"

services:
  app:
    build:
      context: src
      dockerfile: dev.Dockerfile
      args:
        - CONTAINER_USER_ID
    volumes:
      - type: volume
        source: yarn_cache
        target: /yarn-cache
      - ./data/workspaces:/workspaces
      - .env:/env/.env
      - ./data/config:/config
      - ./src:/app
    environment:
      - ENV_FILE=/env/.env
      - CONFIG_DIR=/config
      - NODE_ENV
    labels:
      - "traefik.http.routers.notes.rule=Host(\"${PUBLIC_DOMAIN}\")"
      - "traefik.http.services.notes.loadbalancer.server.port=8080"
    init: true

  traefik:
    image: traefik:v2.6.1
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  yarn_cache:
  generated_certs:
