version: "3.7"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1-alpine
    ports:
      - "${PUBLIC_HOST}:443:443"
      - "${PUBLIC_HOST}:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    depends_on:
      - app

  app:
    build:
      context: src
    volumes:
      - type: volume
        source: yarn_cache
        target: /yarn-cache
      - ./data/workspaces:/workspaces
      - .env:/env/.env
      - ./data/config:/config
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${PUBLIC_DOMAIN}
      - ENV_FILE=/env/.env
      - CONFIG_DIR=/config
    init: true

volumes:
  yarn_cache:
