version: "3.7"

services:
  app:
    image: ghcr.io/zenwarr/notanote:latest
    volumes:
      - ./data/workspaces:/workspaces
      - .env:/env/.env
      - ./data/config:/config
    restart: unless-stopped
    environment:
      - ENV_FILE=/env/.env
      - CONFIG_DIR=/config
    init: true
    networks:
      - traefik
    labels:
      - "traefik.http.routers.notes.rule=Host(\"${PUBLIC_DOMAIN}\")"
      - "traefik.http.services.notes.loadbalancer.server.port=8080"

networks:
  traefik:
    external:
      name: traefik
