version: "3.7"

services:
  app:
    image: ghcr.io/zenwarr/notanote:latest
    volumes:
      - ./data/workspaces:/workspaces
      - .env:/env/.env
      - ./data/config:/config
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${PUBLIC_DOMAIN}
      - ENV_FILE=/env/.env
      - CONFIG_DIR=/config
    init: true
